defaults: &defaults
  adapter: mysql
  username: root
  password: ds85ds85
  socket: /var/run/mysqld/mysqld.sock
#  host: localhost

development:
  database: pt2_dev
  <<: *defaults

test:
  database: pt2_test
  <<: *defaults

production:
  database: pt2
  <<: *defaults
