# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 25) do

  create_table "coming_soons", :force => true do |t|
    t.column "email",      :string
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "drives", :force => true do |t|
    t.column "name", :string
  end

  create_table "engines", :force => true do |t|
    t.column "name", :string
  end

  create_table "makes", :force => true do |t|
    t.column "name", :string
  end

  create_table "messages", :force => true do |t|
    t.column "subject",      :string
    t.column "body",         :text
    t.column "user_id",      :integer
    t.column "from_user_id", :integer
    t.column "unread",       :boolean
    t.column "created_at",   :datetime
    t.column "updated_at",   :datetime
  end

  create_table "models", :force => true do |t|
    t.column "make_id", :integer
    t.column "name",    :string
  end

  create_table "news_items", :force => true do |t|
    t.column "title",      :string
    t.column "summary",    :string
    t.column "article",    :text
    t.column "active",     :boolean
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "photos", :force => true do |t|
    t.column "content_type", :string
    t.column "filename",     :string
    t.column "size",         :integer
    t.column "parent_id",    :integer
    t.column "thumbnail",    :string
    t.column "width",        :integer
    t.column "height",       :integer
    t.column "db_file_id",   :integer
  end

  create_table "project_photos", :force => true do |t|
    t.column "content_type", :string
    t.column "filename",     :string
    t.column "size",         :integer
    t.column "parent_id",    :integer
    t.column "thumbnail",    :string
    t.column "width",        :integer
    t.column "height",       :integer
    t.column "db_file_id",   :integer
    t.column "project_id",   :integer
  end

  create_table "project_steps", :force => true do |t|
    t.column "project_id",       :integer
    t.column "text",             :string
    t.column "project_photo_id", :integer
  end

  create_table "projects", :force => true do |t|
    t.column "title",            :string
    t.column "vehicle_id",       :integer
    t.column "project_photo_id", :integer
    t.column "created_at",       :datetime
    t.column "updated_at",       :datetime
  end

  create_table "service_log_types", :force => true do |t|
    t.column "name", :string
  end

  create_table "service_logs", :force => true do |t|
    t.column "service_log_type_id", :integer
    t.column "vehicle_id",          :integer
    t.column "comments",            :string
    t.column "created_at",          :datetime
    t.column "updated_at",          :datetime
  end

  create_table "transmissions", :force => true do |t|
    t.column "name", :string
  end

  create_table "users", :force => true do |t|
    t.column "login",           :string
    t.column "hashed_password", :string
    t.column "email",           :string
    t.column "salt",            :string
    t.column "created_at",      :datetime
    t.column "lat",             :float
    t.column "lng",             :float
  end

  create_table "vehicle_conditions", :force => true do |t|
    t.column "name", :string
  end

  create_table "vehicle_photos", :force => true do |t|
    t.column "content_type", :string
    t.column "filename",     :string
    t.column "size",         :integer
    t.column "parent_id",    :integer
    t.column "thumbnail",    :string
    t.column "width",        :integer
    t.column "height",       :integer
    t.column "db_file_id",   :integer
    t.column "vehicle_id",   :integer
  end

  create_table "vehicles", :force => true do |t|
    t.column "title",                      :string
    t.column "model_other",                :string
    t.column "year",                       :integer
    t.column "mileage",                    :integer
    t.column "engine_comments",            :text
    t.column "drive_comments",             :text
    t.column "transmission_comments",      :text
    t.column "doors",                      :integer
    t.column "ext_color_comments",         :text
    t.column "int_color_comments",         :text
    t.column "vehicle_condition_comments", :text
    t.column "street_legal",               :boolean
    t.column "additional_comments",        :text
    t.column "active",                     :boolean
    t.column "created_at",                 :datetime
    t.column "updated_at",                 :datetime
    t.column "zipcode",                    :string
    t.column "city",                       :string
    t.column "price",                      :float
    t.column "for_sale",                   :boolean
    t.column "model_id",                   :integer
    t.column "engine_id",                  :integer
    t.column "drive_id",                   :integer
    t.column "transmission_id",            :integer
    t.column "vehicle_condition_id",       :integer
    t.column "user_id",                    :integer
    t.column "lat",                        :float
    t.column "lng",                        :float
  end

end
